# Generated by Django 4.0.4 on 2022-05-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsindexpage',
            options={'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
    ]
